# Generated by Django 3.0.5 on 2020-11-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0002_auto_20201113_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='structure',
            new_name='canonical_smiles',
        ),
    ]
