# Generated by Django 3.0.5 on 2020-11-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0003_auto_20201113_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='created_date',
            new_name='added_date',
        ),
    ]
